project:
  type: website
  output-dir: _site


website:
  title: "OSC"
  image: "images/logo.png"
  favicon: "images/osc_favi.png"
  # google-analytics: "G-FV9Z7SDZ0M"
  # open-graph: true
  twitter-card: true
  site-url: https://github.com/opensourcecourse
  repo-url: https://github.com/opensourcecourse/website
  repo-actions: [edit]
  page-navigation: true

  sidebar: 
    style: "floating"
    collapse-level: 2
    title: "Open Source Course"
    subtitle: 'OSC'
    logo: "images/oss_gateway.png"
    search: true
    contents:
      - index.qmd
      - setup.qmd

      - section: "Modules"
        contents:

        - section: "Git"
          href: modules/git/overview.qmd
          contents:
            - text: 'overview'
              href: modules/git/overview.qmd
            - text: 'slides'
              href: modules/git/slides.qmd
            - text: "exercises"
              href: modules/git/exercises.qmd

        - section: "Style"
          href: modules/style/overview.qmd
          contents:
            - text: 'overview'
              href: modules/style/overview.qmd
            - text: 'slides'
              href: modules/style/slides.qmd
            - text: "exercises"
              href: modules/style/exercises.qmd

        - section: "Linting"
          href: modules/linting/overview.qmd
          contents:
            - text: 'overview'
              href: modules/linting/overview.qmd
            - text: 'slides'
              href: modules/linting/slides.qmd
            - text: "exercises"
              href: modules/linting/exercises.qmd

        - section: "Python: Data Model"
          href: modules/python_data_model/overview.qmd
          contents:
            - text: 'overview'
              href: modules/python_data_model/overview.qmd
            - text: 'slides'
              href: modules/python_data_model/slides.qmd
            - text: "exercises"
              href: modules/python_data_model/exercises.qmd

        - section: "Python: Decorators"
          href: modules/python_decorators/overview.qmd
          contents:
            - text: 'overview'
              href: modules/python_decorators/overview.qmd
            - text: 'slides'
              href: modules/python_decorators/slides.qmd
            - text: "exercises"
              href: modules/python_decorators/exercises.qmd

        - section: "Testing"
          href: modules/testing/overview.qmd
          contents:
            - text: 'overview'
              href: modules/testing/overview.qmd
            - text: 'slides'
              href: modules/testing/slides.qmd
            - text: "exercises"
              href: modules/testing/exercises.qmd

        - section: "Documentation"
          href: modules/documentation/overview.qmd
          contents:
            - text: 'overview'
              href: modules/documentation/overview.qmd
            - text: 'slides'
              href: modules/documentation/slides.qmd
            - text: "exercises"
              href: modules/documentation/exercises.qmd

        - section: "Collaborative Development"
          href: modules/collaborative_development/overview.qmd
          contents:
            - text: 'overview'
              href: modules/collaborative_development/overview.qmd
            - text: 'slides'
              href: modules/collaborative_development/slides.qmd
            - text: "exercises"
              href: modules/collaborative_development/exercises.qmd

        - section: "Continuous Integration"
          href: modules/continuous_integration/overview.qmd
          contents:
            - text: 'overview'
              href: modules/continuous_integration/overview.qmd
            - text: 'slides'
              href: modules/continuous_integration/slides.qmd
            - text: "exercises"
              href: modules/continuous_integration/exercises.qmd

      - acknowledgements.qmd

  navbar:
    background: light
    logo: images/osc_favi.png
    logo-alt: "OSC logo."
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd

    right:
      - icon: github
        href: https://github.com/opensourcecourse/website
        aria-label: OpenSourceCourse GitHub

  
# bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    # include-after-body: js.html
