---
title: "Collaborative Development"
subtitle: "Tools and principles for coding together"
format:
    revealjs:
        slide-number: true
        preview-links: auto
        theme: [../../../custom_slides.scss]
        css: "../../slides.css"
        view-distance: 100
        mobile-view-distance: 100
        navigation-mode: vertical
        controls-layout: bottom-right
        controls-tutorial: true
        embed-resources: true
        mermaid:
            theme: default

footer: \
    <a href="https://opensourcecourse.dev/osc_intro/modules/collaborative_development/overview.html">overview</a> /\
    <a href="https://github.com/opensourcecourse/opencourse/blob/main/osc_intro/modules/collaborative_development/slides.qmd">source</a> /\
    <a href="https://opensourcecourse.dev/osc_intro/modules/collaborative_development/exercises.html">exercises</a>
---


# Collaborative Development

<br>

- Codes of Conduct
- Issues
- Pull Requests
- Code Reviews


# Codes of Conduct

<br>

- Establishes expectations
- Lays out conflict resolution
- Can help establish the tone of a community
- [Contributor covenant](https://www.contributor-covenant.org/) is a popular choice
- Be respectful of others, practice empathy


# Issues

An issue is a petition for a volunteer's time.
Make that petition compelling.

<br>

- Provide enough information to reproduce the issue
- Provide information about your setup
- Be clear about your expectations of the code
- Be patient
- Make suggestions on how to fix, open PR if obvious


# Issues: in the Wild

<br>

Take a look at a few of these issues. Do they make a compelling case? 

- [Obspy 2276](https://github.com/obspy/obspy/issues/2276)
- [Numpy 22585](https://github.com/numpy/numpy/issues/22585)
- [Pandas 50373](https://github.com/pandas-dev/pandas/issues/50373) 
- [Pandas 50473](https://github.com/pandas-dev/pandas/issues/50473)


# Pull Requests
Before you start...

<br>

:::{.incremental}
- See if the project is even active
- Read the developer documentation
- Discuss new features
:::


# Pull Requests

<br>
<br>

```{mermaid}
%%| fig-width: 10
flowchart LR
  A[Bug] --> AA(Issue)
  AA -- Non-obvious fix --> BB(Discuss) 
  AA -- Obvious fix --> CC[Open PR]  
  B[New Feature] --> BB
  BB -- Consensus --> CC
```


# Code Reviews

:::{.incremental}
- Be respectful! 
- Focus on the right things
- Reviews should be a good experience for both parties
- Mentorship occurs in reviews
- Be patient
:::

:::{.footer}
Read more [here](https://google.github.io/eng-practices/review/reviewer/)
:::

# Conclusions

:::{.incremental}
- Be respectful of others
- Get feedback early on
- Get practice with github interfaces
:::

